# fly.toml app configuration file generated for pibipu on 2025-06-15T07:18:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pibipu'
primary_region = 'arn'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
